# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/efficient-contrast',
                'doc_host': 'https://TahaK.github.io',
                'git_url': 'https://github.com/TahaK/efficient-contrast',
                'lib_path': 'efficient_contrast'},
  'syms': {'efficient_contrast.core': {'efficient_contrast.core.foo': ('core.html#foo', 'efficient_contrast/core.py')}}}
